import React from 'react';
import Head from "next/head";
import Hero from "../components/Hero";
import ContactForm from "../components/ContactForm";

const Contact = () => {
    return (
        <div>
            <Head>
                <title>Photography Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Hero heading='ContactForm' message='Submit the form belLow for more work and quotes.'/>
            <ContactForm/>
        </div>
    );
};

export default Contact;