import React from 'react';
import Head from "next/head";
import Hero from "../components/Hero";
import Protfolio from "../components/Protfolio";

const Work = () => {
    return (
        <div>
            <Head>
                <title>Photography Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Hero heading='My Work' message='This is some of my recent work traveling the world.'/>
            <Protfolio/>
        </div>
    );
};

export default Work;